# Generated by Django 4.2.16 on 2025-03-21 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import port_inspector_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('genus_name', models.CharField(max_length=255, unique=True)),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownSpecies',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=255, unique=True)),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('genus', models.JSONField(default=port_inspector_app.models.default_genus)),
                ('species', models.JSONField(default=port_inspector_app.models.default_species)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('specimen_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='port_inspector_app.specimenupload')),
            ],
        ),
    ]
