# Generated by Django 4.2.16 on 2024-12-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("port_inspector_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="port_inspector_app.user",
            ),
        ),
    ]
