# Generated by Django 4.2.16 on 2024-12-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0002_alter_imageset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
