# Generated by Django 4.2.16 on 2024-12-04 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0002_alter_specimenupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
