# Generated by Django 4.2.16 on 2025-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0002_specimenupload_caudal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenupload',
            name='final_identification',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
