# Generated by Django 4.2.16 on 2025-02-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_inspector_app", "0003_alter_specimenupload_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
