# Generated by Django 4.2.16 on 2025-04-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_inspector_app", "0003_specimenupload_final_identification"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.AddField(
            model_name="user", name="is_usda", field=models.BooleanField(default=False),
        ),
    ]
