# Generated by Django 4.1.4 on 2025-04-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0003_specimenupload_final_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_usda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
