# Generated by Django 4.2.16 on 2025-02-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0004_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenupload',
            name='caudal_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='caudal_image', to='port_inspector_app.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='dorsal_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dorsal_image', to='port_inspector_app.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='frontal_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='frontal_image', to='port_inspector_app.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='lateral_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lateral_image', to='port_inspector_app.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specimenupload',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
