# Generated by Django 5.1.2 on 2025-03-04 23:46

import django.db.models.deletion
import port_inspector_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_inspector_app", "0004_user_is_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genus",
            fields=[
                ("id_num", models.AutoField(primary_key=True, serialize=False)),
                ("genus_name", models.CharField(max_length=255, unique=True)),
                ("resource_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnownSpecies",
            fields=[
                ("id_num", models.AutoField(primary_key=True, serialize=False)),
                ("species_name", models.CharField(max_length=255, unique=True)),
                ("resource_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="specimenupload",
            name="genus",
            field=models.JSONField(default=port_inspector_app.models.default_genus),
        ),
        migrations.AddField(
            model_name="specimenupload",
            name="species",
            field=models.JSONField(default=port_inspector_app.models.default_species),
        ),
        migrations.AlterField(
            model_name="specimenupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
