# Generated by Django 5.1.2 on 2025-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port_inspector_app", "0005_genus_knownspecies_specimenupload_genus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genus",
            name="confidence_level",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="knownspecies",
            name="confidence_level",
            field=models.FloatField(default=0.0),
        ),
    ]
