# Generated by Django 5.1.2 on 2025-03-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "port_inspector_app",
            "0006_genus_confidence_level_knownspecies_confidence_level",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="genus",
            name="confidence_level",
            field=models.FloatField(default=0.0),
        ),
    ]
