# Generated by Django 4.2.16 on 2025-03-21 00:30

from django.db import migrations, models
import port_inspector_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0007_alter_specimenupload_caudal_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('genus_name', models.CharField(max_length=255, unique=True)),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnownSpecies',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=255, unique=True)),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='genus',
            field=models.JSONField(default=port_inspector_app.models.default_genus),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='species',
            field=models.JSONField(default=port_inspector_app.models.default_species),
        ),
    ]
